### ISSUE TITLE
Foute zetel persoon datums bij Henk Kamp

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#107]
Lid Henk Kamp heeft een aantal vreemde regels in fractie / zetel / personen:

```sql
select id
,      functie
,      van
,      totenmet
from   fractiezetelpersonen@twk
where  persoon_id = '106805cc-d387-4481-b068-825dc0d6de44'
```

![image](https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/assets/7579444/a5fb6426-2d89-42e8-8f51-7c5dc9807477)

Verwachting is dat de totenmet-datum sowieso niet lager kan zijn dan de van-datum voor het bezet houden van een zetel.

**Comment by OpenDataPortaal** [comment]
Nog wat context bij deze issue. Het gaat hier om data uit het bronsysteem Sesam van voor 2012 (dit gaat ook op voor #108 en gedeeltelijk voor #109). Dit betekent dat het uit een periode komt dat de data niet volledig zijn. Dit stond enkel op de pagina '[Over](https://opendata.tweedekamer.nl/over)' op de website, maar we hebben nu bij de [documentatiepagina's van de entiteitsoorten](https://opendata.tweedekamer.nl/documentatie/persoon) ook toegevoegd uit welk bronsysteem de data komen en vanaf welke periode het beschikbaar is.

Het is ons streven om ooit de periode die de data beslaan verder uit te breiden naar het verleden, maar dat is een project op zichzelf. Vanzelfsprekend blijven datacorrecties wel altijd zeer welkom! De perioden dat Henk Kamp Tweede Kamerlid geweest is zouden moeten zijn: 

- 30 november 2006 - 18 december 2008
- 30 januari 2003 - 27 mei 2003
- 17 mei 1994 - 22 juli 2002

Dit laten we aanpassen.

**Comment by monty241** [comment]
OK, dank! Het zou inderdaad waardevol zijn (hoorde van iemand die het zelfs als onderwerp voor een analytische thesis overwoog), maar ook erg veel werk. Dank voor correctie van dhr. Kamp.
