### ISSUE TITLE
Datafout reis Ernst Cramer

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#108]
De reis naar Werkbezoek vaste commissie voor Verkeer en Waterstaat. omstreeks mei 2008 heeft als startdatum:

5008-05-05

Dit moet vermoedelijk 2008-05-05 zijn.

Verwachting is dat start datum <= tot/met datum is.

![image](https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/assets/7579444/a6f6f0fb-9742-4aff-8a09-27d9b10cbbc6)

**Comment by OpenDataPortaal** [comment]
Nogmaals bedankt voor het doorgeven! We gaan dit voorleggen bij de beheerder van het betreffende bronsysteem.

**Comment by OpenDataPortaal** [comment]
De data zijn aangepast. Dank voor het doorgeven!
