### ISSUE TITLE
Datafout reizen Paul Smeulders en Anja Timmer

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#109]
De onderstaand weergegeven reizen hebben geen einddatum. Dit kan echter niet betekenen dat ze nog voortduren.

![image](https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/assets/7579444/5db21be3-6895-492f-87fc-f504f731751e)

**Comment by OpenDataPortaal** [comment]
De reis van Paul Smeulders is aangepast.

**Comment by OpenDataPortaal** [comment]
#121
