### ISSUE TITLE
Inconsistente schrijfwijze initialen leden

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#110]
De schrijfwijze van van initialen - mogelijk door herkomst uit een ander systeem want lijkt vooral of uitsluitend oudleden te betreffen - is inconsistent.

Voorbeeld obv achternaam = Dijk:

![image](https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/assets/7579444/1fa66129-09a6-4938-afe4-e54b1174fb1a)

Suggestie is om puntgescheiden te gebruiken, zodat ook dubbele voorletters kunnen zoals "Th." voor Theodora.

**Comment by OpenDataPortaal** [comment]
Klopt helemaal: deze waarden zijn inderdaad afkomstig uit een ander systeem. Ambitie is om deze waarden consistent te maken, maar dit zal op langere termijn zijn.

**Comment by OpenDataPortaal** [comment]
#121
