### ISSUE TITLE
Dubbele punt in content-disposition van xml verslagen

### ISSUE THREAD

**Issue by SiggyF** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#116]
Als ik een resource opvraag van een verslag dan krijg ik een filenaam terug met twee punten voor de extensie.
Ik had verwacht een enkele punt te krijgen tussen filenaam en extensie.

Een voorbeeld request is de resource `cdc70ea8-279d-457b-b0ea-bff9bb5797ed`. 
```
curl -sD - -o /dev/null 'https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Resources/cdc70ea8-279d-457b-b0ea-bff9bb5797ed'
```

Deze hoort bij verslag `cdc70ea8-279d-457b-b0ea-bff9bb5797ed`, bij vergadering `df6522e0-3290-41a3-8fe8-ff2d70762a00`.   Als ik kijk naar de http response dan zie ik een dubbele punt (`..`) bij het veld `Content-Disposition`.  Hierdoor krijgt de file een naam met een dubbele punt in plaats van een enkele. Dit kan men reproduceren met bijvoorbeeld het commando `wget --content-disposition 'https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Resources/cdc70ea8-279d-457b-b0ea-bff9bb5797ed'`.

De volledige header is:
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 258587
Content-Type: text/xml
Expires: -1
Content-Disposition: inline; filename=cdc70ea8-279d-457b-b0ea-bff9bb5797ed..xml
Content-Security-Policy: default-src 'self'; frame-ancestors 'self'
Date: Sat, 12 Aug 2023 12:14:14 GMT
Set-Cookie: XXX; Path=/; Domain=.gegevensmagazijn.tweedekamer.nl
```

De incorrecte filenaam is:
**`filename=cdc70ea8-279d-457b-b0ea-bff9bb5797ed..xml`**
Ik had hier verwacht:
**`filename=cdc70ea8-279d-457b-b0ea-bff9bb5797ed.xml`**

Ik zie dit probleem ook bij andere resources, bijvoorbeeld `https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Resources/98a7aceb-516b-4a89-a29e-446db0e64e90` van dezelfde vergadering. 

Kunt u de dubbele punt vervangen door een enkele punt?

Alvast bedankt!

**Comment by OpenDataPortaal** [comment]
Bedankt voor het doorgeven. We hebben het voorgelegd aan de beheerders. Na hun eerste analyse doen ze nu aanvullend onderzoek. Je hoort zo snel mogelijk van ons.

**Comment by OpenDataPortaal** [comment]
Met het uitrollen van de laatste update zou dit opgelost moeten zijn.
