### ISSUE TITLE
Begin en einddatum omgedraaid voor Henk Kamp (ID 106805cc-d387-4481-b068-825dc0d6de44) in FractieZetelPersoon

### ISSUE THREAD

**Issue by G00mbah** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#117]
Goedemiddag!

De datum 'Van' is tot tweemaal verder in de toekomst voor Henk Kamp in FractieZetelPersoon dan 'TotEnMet'. 

Bijvoorbeeld: 

Van - 2006-11-29T23:00:00+00:00

TotEnMet - 2003-02-21T23:00:00+00:00

Vriendelijke groet,

Joshua Hazelaar

**Comment by OpenDataPortaal** [comment]
Bedankt voor het doorgeven. We hebben het doorgegeven aan de beheerder van het betreffende bronsysteem. Kijk ook even bij [#107](https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/issues/107): daar wat context bij de achtergrond van dit issue.

**Comment by OpenDataPortaal** [comment]
#121
