### ISSUE TITLE
Verwijderde activiteiten

### ISSUE THREAD

**Issue by breyten** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#128]
Ik heb een aantal activiteiten die ik oorpsornkelijk wel heb binnegehaald (Odata), maar die inmiddels niet meer bestaan.

Zo heb ik een activiteit met de oorspronkelijk bijbehorende url `https://www.tweedekamer.nl/debat_en_vergadering/commissievergaderingen/details?id=2024A01262` (De oorspronkelijke titel was 'volgt' met de start- en eindtijd 2024-04-11 14:00:00+00:00 - 2024-04-11 15:30:00+00:00). Het bijbehorende Id is `26d92d18-12ee-40c4-aaf8-812de8e94b80`.

Inmiddels levert de pagina op tweedekamer.nl een 404 op -- maar ook het bijbehorende request naar `https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Document/26d92d18-12ee-40c4-aaf8-812de8e94b80` levert ook een 404 op.

Is er een manier om er met de api achter te komen wanneer dit gebeurt? Zou dit niet gereflecteerd moeten worden in het `Verwijderd` attribuut van de activiteit?

**Comment by OpenDataPortaal** [comment]
De OData API geeft aan dat de betreffende entiteit is verwijderd alleen wordt er in de gegeven _query_ `/Document` gebruikt in plaats van `/Activiteit`, zie:

https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Activiteit/26d92d18-12ee-40c4-aaf8-812de8e94b80
