### ISSUE TITLE
Queeny Rajkowski zetel tot/met 7 december ipv tot/met 5 december 2023.

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#135]
Via de volgende query:

```sql
  select /*+ http_disk_cache(false) http_memory_cache(false) */ totenmet
  from   FractieZetelPersonen@twk t
  --
  -- Only members that are currently active in Tweede Kamer or
  -- have been active in the current Tweede Kamer.
  --
  where  totenmet is not null
and totenmet >= to_date('20231206', 'YYYYMMDD')
  and    t.verwijderd = false
and  persoon_id = '4bf69aa9-29a7-44db-b7ee-8bfa40e343dd'
```

blijkt dat Queeny (en sommige andere leden) op 6 en 7 december nog in de tweede kamer zaten:

| Van | Totenmet |
|---|---|
| 2021-03-30 | 2023-12-07 |
| 2024-03-29 | null |

De URL voor de eerste regel is:

> https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/FractieZetelPersoon?$filter=Persoon_Id%20eq%204bf69aa9-29a7-44db-b7ee-8bfa40e343dd%20and%20Verwijderd%20eq%20false%20and%20TotEnMet%20ne%20null%20and%20TotEnMet%20ge%202023-12-06T00:00:00Z

met als antwoord:

```json
"Van":"2021-03-31T00:00:00+02:00","TotEnMet":"2023-12-07T00:00:00+01:00"
```

Er kan geredetwist worden over het gebruik van tijd op dit veld en zeker in combinatie met tijdzones / DST, maar volgens https://www.tweedekamer.nl/nieuws/persberichten/tijdlijn-verkiezingen-en-formatie is de nieuwe Tweede Kamer op 6 december beedigd.

Ik zou dan verwachten dat de tot/met datum 5 december 2023 zou zijn geweest, en niet 7 december.

**Comment by OpenDataPortaal** [comment]
Het klopt dat de nieuwe Tweede Kamer is beëdigd op 6 december 2023. 

Queeny Rajkowski is toen ook beëdigd. Ze zat na die datum dus nog in de Kamer omdat ze is herkozen als Kamerlid. Echter is zij - samen met nog twee andere Kamerleden - vervangen, omdat zij op 8 december met zwangerschapsverlof ging. Zie ook dit nieuwsbericht: https://www.tweedekamer.nl/nieuws/kamernieuws/drie-kamerleden-beedigd-0

**Comment by monty241** [comment]
Dank voor de snelle en uitgebreide toelichting. Een soortgelijk probleem was inderdaad bij meerdere kamerleden gevonden.

De (impliciete) verwachting was dat de fractie zetel persoon entiteit ook een relatie heeft naar zittingsperiode en er daarom dan twee rijen zouden zijn. Ik begrijp dat dit niet het geval is.

Is er een wijze om de zittingsperiodes te relateren naar de personen?

Het lukt niet om iets daarvoor te vinden, maar het model lijkt onder water wel (handmatige of automatische) relaties te kennen naar de zittingsperiode zoals "AantalStemmen" en "AantalZetels" bij fractie.

**Comment by OpenDataPortaal** [comment]
Helaas zit de zittingsperiode niet expliciet in de data. Dit is iets waar we op de achtergrond wel mee aan de slag zijn, maar op dit moment wordt er in de bronsystemen weinig rekening mee gehouden. We hebben nog even onderzocht of de beëdiging van een nieuwe Kamer eenduidig uit de entiteitsoort Activiteit gehaald kan worden om hier de datums van te gebruiken voor de zittingsperioden, maar dit bleek niet het geval.

De enige manier die we nu zo gauw konden bedenken vereist handmatig de datums van het begin en eind van de zittingsperiode te gebruiken in combinatie met waarden uit de entiteitsoort FractieZetelpersoon. Voor de huidige zittingsperiode bijvoorbeeld:
[https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=FractieZetelPersoon/any(a:a/TotEnMet ge 2023-12-06 or a/TotEnMet eq null)](https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=FractieZetelPersoon/any(a:a/TotEnMet%20ge%202023-12-06%20or%20a/TotEnMet%20eq%20null))

En voor de vorige zittingsperiode:
[https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=FractieZetelPersoon/any(a:a/Van lt 2021-03-31 and (a/TotEnMet ge 2021-03-31 or a/TotEnMet eq null)) or FractieZetelPersoon/any(a:a/Van ge 2021-03-31 and a/Van le 2023-12-05)](https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=FractieZetelPersoon/any(a:a/Van%20lt%202021-03-31%20and%20(a/TotEnMet%20ge%202021-03-31%20or%20a/TotEnMet%20eq%20null))%20or%20FractieZetelPersoon/any(a:a/Van%20ge%202021-03-31%20and%20a/Van%20le%202023-12-05))

Tot slot gaan we nog voorleggen of tijdzone en tijd uit deze kolommen gehaald kunnen worden. Het klopt inderdaad dat deze gegevens hierbij irrelevant zijn en we zijn dit ook voor andere kolommen aan het doen (#78).

**Comment by monty241** [comment]
Dank je wel voor toelichting; goed om te weten dat we er niet naastgekeken hebben. Wie weet ooit in de toekomst beschikbaar.

**Comment by OpenDataPortaal** [comment]
Staat zeker op de lijst!

**Comment by OpenDataPortaal** [comment]
#121
