### ISSUE TITLE
Ontbrekende afbeeldingen zoals dhr. Faddegon

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#136]
In de API is momenteel niks te vinden qua afbeelding voor bijvoorbeeld dhr. Faddegon (of mw. A. Heite):

```
select t.*
from   PersonenExtra@twk t
where achternaam = 'Faddegon'
```

Zie https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=Achternaam%20eq%20%27Faddegon%27:

```json
{"@odata.context":"https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/$metadata#Persoon","value":[{"Id":"111864bd-b826-4e5c-880f-29565140329f","Nummer":62412,"Titels":null,"Initialen":"C.J.","Tussenvoegsel":null,"Achternaam":"Faddegon","Voornamen":"Christian Joseph","Roepnaam":"Chris","Geslacht":"man","Functie":"Tweede Kamerlid","Geboortedatum":"1954-08-18T00:00:00+02:00","Geboorteplaats":"Delfzijl","Geboorteland":"Nederland","Overlijdensdatum":null,"Overlijdensplaats":null,"Woonplaats":"'s-Gravenhage","Land":"NL","Fractielabel":null,"ContentType":null,"ContentLength":null,"GewijzigdOp":"2024-07-04T14:37:28+02:00","ApiGewijzigdOp":"2024-07-04T12:38:24.5430559Z","Verwijderd":false}]}
```

Echter, op de site van de Tweede Kamer is op hetzelfde moment WEL een afbeelding zichtbaar:

https://www.tweedekamer.nl/kamerleden_en_commissies/alle_kamerleden/faddegon-cj-pvv

![image](https://github.com/user-attachments/assets/ffbd2d0b-eb90-4793-8a47-d6391560f120)

Is het mogelijk om deze afbeeldingen ook beschikbaar te stellen via de API?

**Comment by OpenDataPortaal** [comment]
De afbeeldingen in het Gegevensmagazijn zijn (nog) niet aan de website gekoppeld. In het kader van #106 zijn we hier nog mee bezig maar op dit moment wordt het betreffende bronsysteem geüpdatet waardoor dit even in de wacht staat.

**Comment by monty241** [comment]
OK, clear, thx. We zullen op andere wijze verwerken waar kan.
