### ISSUE TITLE
HTTP 500 error

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#137]
Bij het opvragen van de volgende URL in browser:

```
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=Verwijderd%20eq%20false
```

komt op 27-07-2024 09:46 CET een foutmelding terug met HTTP 500:

```json
{"error":{"code":"","message":"An error has occurred."}}
```

Deze foutmelding komt ook vanaf andere IP-adressen terug.

Het is fijn als deze foutmelding opgelost kan worden.

Daarnaast is de suggestie om een code of melding toe te voegen zodat het enigszins te interpreteren is als een tijdelijke of blijvende fout.

**Comment by monty241** [comment]
Deze foutmelding treedt ook ongefilterd op:

```
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon
```

Deze geeft ook:

```json
{"error":{"code":"","message":"An error has occurred."}}
```

**Comment by OpenDataPortaal** [comment]
Bedankt voor het melden! Er lijkt een probleem te zijn ontstaan bij het repliceren van het lokale Gegevensmagazijn naar de cloud naar aanleiding van deze update: https://opendata.tweedekamer.nl/nieuws/update-op-26-juli-2024 

We zijn bezig om dit op te lossen en gaan ook even een bericht op de website plaatsen.

**Comment by monty241** [comment]
Dank! Normaal kan de brondata niet vervangen worden als er iets fout wordt, door een fout aan onze kant ligt nu ook de eigen replica er uit.
