### ISSUE TITLE
In queries werken niet meer

### ISSUE THREAD

**Issue by ikjelle** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#139]
Sinds 29 juli 9:46, geeft de query `https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Besluit?$filter=Status%20in%20(%27Voorstel%27)` een 500. Hiervoor werkte de query nog wel. (Op 29 juli 9:41 is de laatste succesvolle query)

Mijn vermoeden is dat de `in` query is aangepast en nu stuk gaat.

**Comment by OpenDataPortaal** [comment]
Bedankt voor de melding! We hebben dit doorgegeven bij de technisch beheerders. Het lijkt er inderdaad op dat dit niet meer werkt sinds de laatste update.

**Comment by OpenDataPortaal** [comment]
Het is opgelost. IN kan weer gebruikt worden in query's.
