### ISSUE TITLE
Definitie veld woonplaats personen

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#140]
Hoe is de woonplaats gedefinieerd?

## Derk Boswijk: woonplaats veld bevat dorp, niet gemeente

Bij Derk Boswijk staat Kockengen:

> https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=Achternaam%20eq%20%27Boswijk%27

maar Kockengen is onderdeel gemeente Woerden en geen woonplaats volgens CBS.

## Habtamu de Hoop: woonplaats veld bevat vervallen gemeente, niet dorp

Terwijl bij Habtamu de Hoop staat Sneek:

> https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon?$filter=Achternaam%20eq%20%27Hoop%27

maar volgens https://groenlinkspvda.nl/onze-mensen/habtamu-de-hoop/ woont hij in "Wommels", onderdeel van gemeente "Súdwest-Fryslân".

"Sneek" lijkt onderdeel te zijn van de gemeente "Súdwest-Fryslân". "Wommels" is niet bekend als woonplaats in CBS 84992NED.

## Vraag

Is de woonplaats bij Persoon gedefinieerd als de woonplaats volgens CBS 84992NED? Of is dit free-format want Sneek is vervallen?

## Relevantie

In de politiek wordt soms gesproken over regionale representatie. Dan is het handig als je betrouwbaar kunt bepalen welk lid in welke regio woont, net zoals dat in de VS relevant is.

**Comment by OpenDataPortaal** [comment]
Woonplaatsinformatie wordt door fracties aangeleverd en is niet gestandaardiseerd. We vinden dit wel een goed idee en gaan in ieder geval voorleggen of de invoer beperkt kan worden tot daadwerkelijke woonplaatsen. Voor de data zoals die nu is zullen we moeten kijken of er een valide manier is om deze te corrigeren (e.g. hoe om te gaan met de woonplaatsen van Tweede Kamerleden uit het verleden). De [CBS-data](https://www.cbs.nl/nl-nl/cijfers/detail/85877NED?q=woonplaatsen) is in ieder geval een goed referentiepunt, bedankt voor verwijzing. 

Omdat we (helaas)  verwachten dat dit niet snel opgepakt gaat worden voegen we het voor nu toe aan #121. Dan wordt het in ieder geval meegenomen wanneer we een volgende stap gaan zetten met actorenmanagement.

**Comment by monty241** [comment]
Dank voor update. Het is niet anders. We beperken voorlopig tot enkel kunnen zoeken op naam en niet op regio zoals:

![image](https://github.com/user-attachments/assets/8cc1146e-265a-4d7f-b714-09709ab0d03b)
