### ISSUE TITLE
Aanwezigheid/presentie debat/overleg

### ISSUE THREAD

**Issue by monty241** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#141]
Alhoewel mogelijk een edge case van de inzet, is er een mogelijkheid om ook de aanwezigheid/presentie van de leden bij overleggen op te vragen via de API?

Ik weet dat ze tekenen voor aanwezigheid, maar kan niet terugvinden.

**Comment by breyten** [comment]
Volgens mij zou je het terug moeten kunnen vinden via https://opendata.tweedekamer.nl/documentatie/activiteitactor  en de bijbehorende activiteit (zelf nog niet geprobeerd :))

**Comment by OpenDataPortaal** [comment]
Een belangrijke kanttekening hierbij is dat aanwezigheid en deelname niet hetzelfde zijn. Informatie over aanwezigheid is op dit moment alleen nog te vinden in de verslagen. We zijn op dit moment wel bezig om de data uit de XML achter de entiteitsoort [Verslag](https://opendata.tweedekamer.nl/documentatie/verslag) te vertalen naar tabellen die we via het Gegevensmagazijn beschikbaar willen stellen (in het verlengde van #95). Intern draait dit nu en zijn we het druk aan het testen. 

Informatie over geplande deelname is inderdaad via de relatie tussen [Activiteit](https://opendata.tweedekamer/documentatie/activiteit) en [ActiviteitActor](https://opendata.tweedekamer/document/activiteitactor) op te halen. Het is in dit geval **geplande deelname** daar als iemand niet komt opdagen dit wel wordt gereflecteerd door het verslag maar de betreffende gegevens in het bronsysteem (ActiviteitActor) helaas niet worden aangepast door de Griffie. We zijn op dit moment bezig om de documentatie te herzien om dit soort feiten beter vast te leggen. 

Voor commissievergaderingen komt beoogde deelname en aanwezigheid overigens vaak overeen. Voor plenaire vergaderingen komt het vaker voor dat er meer aanwezigen zijn dan deelnemers (sprekers). Hieronder nog een voorbeeld hoe geplande deelname opgehaald kan worden van een Activiteit:

[https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Activiteit/a7fbfbe6-48ee-4182-b9ed-f49d34be4eab?$expand=ActiviteitActor($filter=relatie eq 'Deelnemer')](https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Activiteit/a7fbfbe6-48ee-4182-b9ed-f49d34be4eab?$expand=ActiviteitActor($filter=relatie%20eq%20%27Deelnemer%27))

**Comment by monty241** [comment]
Dank Breyten en OpenDataPortaal voor toelichting! Ik begrijp dat de geplande aanwezigheid beschikbaar is, maar de daadwerkelijke beschikbaarheid nog niet.

De oorspronkelijke vraag betreft inderdaad de daadwerkelijke presentie tijdens de activiteit.

Fijn dat er een traject loopt om deze informatie geautomatiseerd inzichtelijk te maken; we zullen hier op wachten.
