### ISSUE TITLE
tkData-v1-0-toezegging.xsd: use of undefined type referentieBijgewerktLiteral

### ISSUE THREAD

**Issue by bwbroersma** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#144]
https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/blob/3f9b0e755a024e48801d6ee0fedd4332252a1b24/xsd/tkData-v1-0-toezegging.xsd#L30-L32

The `referentieBijgewerktLiteral` type is not defined. Please include the definition so the XSD can be compiled.

**Comment by OpenDataPortaal** [comment]
https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/commit/c8f21453a46139f5241b05a967092d5b7730c423
