### ISSUE TITLE
Spreker uuid in Verslag XML en in Persoon tabel verschillend

### ISSUE THREAD

**Issue by berthubert** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#151]
Goedendag,

In de VLOS XML in de enclosure van de Verslag category zijn er "sprekers", en die hebben ook een UUID. 

Mevrouw Kathmann is bijvoorbeeld in verslagen `<spreker soort="Tweede Kamerlid" objectid="f0d495ee-e422-4d4a-9f12-9e1ad3fa934d">`

Helaas komt dit UUID niet overeen met de UUID in de Persoon tabel, alwaar mw Kathmann 9e79de98-e914-4dc8-8dc7-6d7cb09b93d7 is

Is er ergens een mapping tussen deze twee UUIDs? Dat zou de analyse een heel stuk makkelijker maken.

Dank!

**Comment by OpenDataPortaal** [comment]
Helaas is er inderdaad geen relatie tussen deze twee id's. We zijn wel bezig om hier een soort koppeling tussen te maken (#95).
