### ISSUE TITLE
Layout documentatie pagina

### ISSUE THREAD

**Issue by svrooij** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#72]
De documentatie pagina schaalt wel, maar er wordt niet echt goed gebruik gemaakt van de beschikbare scherm grote.

Heel veel wit ruimte rondom de tekst.

![Screenshot_20220623-075021.png](https://user-images.githubusercontent.com/1292510/175225058-e4b7ba9b-0e93-4842-9204-e273ffeef07c.png)

**Comment by OpenDataPortaal** [comment]
Bedankt voor het melden! Hier gaan we mee aan de slag. Bij het reproduceren stuitten we ook op een blok zonder inhoud die ruimte inneemt op de [landingspagina](https://opendata.tweedekamer.nl/) en [nieuwspagina](https://opendata.tweedekamer.nl/nieuws) bij een resolutie van <768px. Hier gaan we ook wat aan laten doen.

**Comment by OpenDataPortaal** [comment]
Om de website te laten voldoen aan WCAG 2.0 niveau AA is er een rapport opgesteld door een externe partij. We hebben alle hiaten aangeleverd bij de technisch beheerder (tevens extern) van de website. Zij gaan hier nu mee verder aan de slag. Het blok zonder inhoud is al weggehaald.
