### ISSUE TITLE
Ophalen gerelateerde documenten (oData)

### ISSUE THREAD

**Issue by JoinSeven** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#75]
Goedemorgen, 

Wij hebben een vraag omtrent het ophalen van gerelateerde documenten (dus geen bijlagen). 
We voeren momenteel een query uit met de volgende beschikbare expand parameters: DocumentVersie, BronDocument, BijlageDocument, HuidigeDocumentVersie, DocumentActor, Kamerstukdossier, Zaak, Activiteit & Agendapunt maar zien geen gerelateerde documenten terugkomen.

Neem bijvoorbeeld [dit kamerstuk](https://www.tweedekamer.nl/kamerstukken/kamervragen/detail?id=2019Z05743&did=2019D16854). Op de website zien we daar twee gerelateerde documenten, maar in de JSON zien we deze niet:

{
    "Id": "ec9315bf-e1d1-422e-a8fb-0000932ed927",
    "Soort": "Antwoord schriftelijke vragen",
    "DocumentNummer": "2019D16854",
    "Titel": null,
    "Onderwerp": "Antwoord op vragen van het lid Van Nispen over het mogelijk strafrechtelijke karakter van het sluiten van drugspanden door de burgemeester ",
    "Datum": "2019-04-24T00:00:00+02:00",
    "Vergaderjaar": "2018-2019",
    "Kamer": 2,
    "Volgnummer": -1,
    "Citeertitel": null,
    "Alias": null,
    "DatumRegistratie": "2019-04-23T00:00:00+02:00",
    "DatumOntvangst": null,
    "Aanhangselnummer": "181902411",
    "KenmerkAfzender": null,
    "Organisatie": "Tweede Kamer",
    "ContentType": "application/pdf",
    "ContentLength": 32150,
    "GewijzigdOp": "2022-04-26T09:55:26.683+02:00",
    "ApiGewijzigdOp": "2022-04-30T16:43:22.8081028Z",
    "Verwijderd": false,
    "DocumentVersie": [
        {
            "Id": "106ec4cb-db43-4ab2-9aed-01a5b756b58d",
            "Status": "Vrijgegeven",
            "Versienummer": 1,
            "Bestandsgrootte": 108,
            "Extensie": ".docx",
            "Datum": "2019-04-23T10:51:58.693+02:00",
            "GewijzigdOp": "2019-10-21T10:22:48.577+02:00",
            "ApiGewijzigdOp": "2019-10-21T09:12:23.7939704Z",
            "Verwijderd": false,
            "Document_Id": "ec9315bf-e1d1-422e-a8fb-0000932ed927"
        },
        {
            "Id": "ffb35c1c-da22-45d4-919d-3fa9c400567f",
            "Status": "Vrijgegeven",
            "Versienummer": 3,
            "Bestandsgrootte": 47,
            "Extensie": ".pdf",
            "Datum": "2019-04-26T13:50:52.757+02:00",
            "GewijzigdOp": "2019-10-21T10:22:53.213+02:00",
            "ApiGewijzigdOp": "2019-10-21T10:35:53.3975182Z",
            "Verwijderd": false,
            "Document_Id": "ec9315bf-e1d1-422e-a8fb-0000932ed927"
        },
        {
            "Id": "bda61cb5-4e37-4457-9aa9-cc8bc6db8072",
            "Status": "Vrijgegeven",
            "Versienummer": 2,
            "Bestandsgrootte": 32,
            "Extensie": ".doc",
            "Datum": "2019-04-25T13:13:48.42+02:00",
            "GewijzigdOp": "2019-10-21T10:22:57.427+02:00",
            "ApiGewijzigdOp": "2019-10-21T11:59:28.9753681Z",
            "Verwijderd": false,
            "Document_Id": "ec9315bf-e1d1-422e-a8fb-0000932ed927"
        }
    ],
    "BronDocument": [],
    "BijlageDocument": [],
    "HuidigeDocumentVersie": {
        "Id": "ffb35c1c-da22-45d4-919d-3fa9c400567f",
        "Status": "Vrijgegeven",
        "Versienummer": 3,
        "Bestandsgrootte": 47,
        "Extensie": ".pdf",
        "Datum": "2019-04-26T13:50:52.757+02:00",
        "GewijzigdOp": "2019-10-21T10:22:53.213+02:00",
        "ApiGewijzigdOp": "2019-10-21T10:35:53.3975182Z",
        "Verwijderd": false,
        "Document_Id": "ec9315bf-e1d1-422e-a8fb-0000932ed927"
    },
    "DocumentActor": [
        {
            "Id": "bffe98f7-acf7-464d-a82e-95c31194fb49",
            "Document_Id": "ec9315bf-e1d1-422e-a8fb-0000932ed927",
            "ActorNaam": "F.B.J. Grapperhaus",
            "ActorFractie": null,
            "Functie": "minister van Justitie en Veiligheid",
            "Relatie": "Eerste ondertekenaar",
            "SidActor": "S-1-365867521-2120874753-1363728866-1133790722-4112211636-101436480",
            "GewijzigdOp": "2019-10-21T11:45:07.76+02:00",
            "ApiGewijzigdOp": "2019-10-21T21:22:24.554913Z",
            "Verwijderd": false,
            "Persoon_Id": "b05c47d7-4895-47f8-b972-009c1ca90107",
            "Fractie_Id": null,
            "Commissie_Id": null
        }
    ],
    "Kamerstukdossier": [],
    "Zaak": [
        {
            "Id": "ec1c32a7-37f3-4668-91a3-a25f3d40e52b",
            "Nummer": "2019Z05743",
            "Soort": "Schriftelijke vragen",
            "Titel": null,
            "Citeertitel": null,
            "Alias": null,
            "Status": "Vrijgegeven",
            "Onderwerp": "Het mogelijk strafrechtelijke karakter van het sluiten van drugspanden door de burgemeester ",
            "GestartOp": "2019-03-25T00:00:00+01:00",
            "Organisatie": "Tweede Kamer",
            "Grondslagvoorhang": null,
            "Termijn": null,
            "Vergaderjaar": "2018-2019",
            "Volgnummer": -1,
            "HuidigeBehandelstatus": null,
            "Afgedaan": true,
            "GrootProject": false,
            "Kabinetsappreciatie": null,
            "GewijzigdOp": "2019-10-17T15:22:23.043+02:00",
            "ApiGewijzigdOp": "2019-10-17T13:56:16.7228499Z",
            "Verwijderd": false
        }
    ],
    "Activiteit": [],
    "Agendapunt": []
}

Hoe zouden we, bijvoorbeeld voor dit specifieke document, de gerelateerde documenten uit de API kunnen halen?

**Comment by OpenDataPortaal** [comment]
Documenten zijn aan elkaar gerelateerd via de entiteitsoort Zaak. In dit geval is het dus mogelijk om via de bijbehorende Zaak met een `$expand` de daaraan gerelateerde Documenten op te vragen:
[gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/zaak(ec1c32a7-37f3-4668-91a3-a25f3d40e52b)?$expand=document  ](
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/zaak(ec1c32a7-37f3-4668-91a3-a25f3d40e52b)?$expand=document  )

Als het Document het startpunt moet zijn, kan het ook met de volgende _query_:
[gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/document(ec9315bf-e1d1-422e-a8fb-0000932ed927)?$expand=zaak($expand=document)](https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/document(ec9315bf-e1d1-422e-a8fb-0000932ed927)?$expand=zaak($expand=document))

Op deze manier gaan we met een `$expand` vanaf het Document naar de bijbehorende Zaak, en vervolgens met een `$expand `op de Zaak naar alle bijbehorende Documenten. Het Document dat het startpunt was zit hier dan wel ook weer bij. 

Hopelijk helpt dit!
