### ISSUE TITLE
Stemming informatiemodel/documentatie lijkt niet te kloppen

### ISSUE THREAD

**Issue by jorisrs** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#76]
Documentatie:
`Een-op-een | Fractie, Persoon`

Moet dit niet zijn:
`Veel-op-een | Fractie, Persoon`

**Comment by OpenDataPortaal** [comment]
Inderdaad! Bedankt voor het doorgeven. We gaan dit aanpassen.

**Comment by OpenDataPortaal** [comment]
Het [informatiemodel](https://opendata.tweedekamer.nl/documentatie/informatiemodel) en de documentatiepagina's over de entiteitsoorten [Fractie,](https://opendata.tweedekamer.nl/documentatie/fractie) [Persoon](https://opendata.tweedekamer.nl/documentatie/persoon) en [Stemming](https://opendata.tweedekamer.nl/documentatie/stemming) zijn aangepast.
