### ISSUE TITLE
Inconsistentie functieomschrijving

### ISSUE THREAD

**Issue by jorisrs** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#77]
Onder persoon -> functie zijn er drie mogelijkheden:

- Oud Kamerlid
- Eerste kamerlid
- Tweede Kamerlid

Oud- en Tweede Kamerleden is K met hoofdletter, bij 1e Kamer niet.

**Comment by OpenDataPortaal** [comment]
Dat is inderdaad incorrect. Kamerlid moet in alle drie de gevallen met een hoofdletter zijn. We gaan dit doorgeven bij de beheerders van het betreffende bronsysteem. Bedankt voor het doorgeven!

**Comment by OpenDataPortaal** [comment]
De schrijfwijze is aangepast in het bronsysteem en daarmee ook in de data die met de API's is op te halen.
