### ISSUE TITLE
Documentatie nevenfuncties

### ISSUE THREAD

**Issue by jorisrs** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#79]
Onder PersoonNevenfunctie

- Gewicht mist in documentatie
- Vergoedingsoort -> O>m<kostenvergoeding, moet zijn Onkostenvergoeding (Alleen in documentatie, data is goed)
- Omschrijving kan langer zijn dan 255, zie b.v. 4393a496-a09c-4a66-ad25-d804e81aace1 (403 karakters)

**Comment by OpenDataPortaal** [comment]
Het is aangepast. Fijn dat er iemand zo strak naar de documentatie kijkt. We hopen de documentatietabellen in de toekomst grotendeels automatisch te kunnen genereren, maar voor nu is het nog even mensenwerk. Veel dank!
