### ISSUE TITLE
Laatste bevindingen persoon* entiteiten

### ISSUE THREAD

**Issue by jorisrs** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#80]
PersoonContactinformatie
Soort -> LinkedIn documentatie, maar Linkedin in data. (dus zonder hoofdletter 'i')

PersoonReis
Van/TotEnMet 'Datetime2' maar ik zie alleen datums in de data
BetaaldDoor mist in documentatie

PersoonLoopban
Van/TotEnMet 'Datetime2' maar ook hier alleen datums (soms alleen jaartal) in data
Functie mist in documentatie
OmschrijvingNl/En geeft aan 255 max, maar kan ook langer zijn. b.v. 95a24091-b385-436e-bc3e-aaee5402e59a (284 karakters)

PersoonOnderwijs
OpleidingEn mist
Van/TotEnMet 'Datetime2' maar ook hier alleen datums (soms alleen jaartal) in data

**Comment by OpenDataPortaal** [comment]
Gerelateerd aan #78 en #79.

**Comment by OpenDataPortaal** [comment]
De schrijfwijze van LinkedIn is aangekaart bij de beheerders van het betreffende bronsysteem en de documentatiepagina's  [PersoonReis](https://opendata.tweedekamer.nl/documentatie/persoonreis), [PersoonLoopbaan](https://opendata.tweedekamer.nl/documentatie/persoonloopbaan) en [PersoonOnderwijs](https://opendata.tweedekamer.nl/documentatie/persoononderwijs) zijn aangepast.

**Comment by OpenDataPortaal** [comment]
Schrijfwijze van LinkedIn is nu ook gecorrigeerd.
