### ISSUE TITLE
SyncFeed API geeft altijd een Error voor categorie ZaakActor

### ISSUE THREAD

**Issue by jordibeen** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#84]
Wanneer je via de SyncFeed API de ZaakActor's ophaalt krijgt je altijd de volgende error response terug:

URL: https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed?category=ZaakActor
Response:
```
<Error>
    <Message>An error has occurred.</Message>
</Error>
```

**Comment by jordibeen** [comment]
Hi, is er zicht op wanneer het ZaakActor endpoint weer beschikbaar is?

**Comment by OpenDataPortaal** [comment]
We zijn helaas nog niet aan het oplossen toegekomen. Eind september verwachten we een duidelijkere tijdsindicatie te kunnen geven. We begrijpen dat dit onhandig is en daarom ook onze excuses voor het ongemak.

**Comment by OpenDataPortaal** [comment]
Helaas kunnen we nog geen duidelijkere tijdsindicatie geven daar er interne projecten zijn met voorrang die ook aansluiten op het Gegevensmagazijn. Zodra er meer informatie is maken we dit kenbaar.

**Comment by OpenDataPortaal** [comment]
Het probleem met entiteiten van de entiteitsoort ZaakActor in de SyncFeed API zou nu opgelost moeten zijn. Als dit niet het geval is dan horen we dat graag (incl. tijdstip van de poging zodat we in de logs kunnen kijken).

**Comment by jordibeen** [comment]
Het is tot op heden helaas nog niet mogelijk om de entiteitsoort ZaakActor op te halen via de SyncFeed API. Ik heb zojuist een paar pogingen gedaan. (2022-11-03T18:18+0100).

**Comment by OpenDataPortaal** [comment]
We zijn er inderdaad achter dat het probleem met ZaakActor en Besluit (#89) nog niet duurzaam is opgelost: soms werkt het, vaak niet. Er wordt op dit moment actief aan een oplossing gewerkt, evenals aan een oplossing voor het filteren op attribuutwaarden in de SyncFeed API (#85). Helaas blijken de problemen complexer dan verwacht omdat het in de communicatie tussen systemen misgaat, en niet aan de programmatuur van de API zelf ligt.

**Comment by OpenDataPortaal** [comment]
Er is een tijdelijke oplossing geïmplementeerd die ervoor zou moeten zorgen dat de entiteitsoort ZaakActor beschikbaar blijft in de SyncFeed API. Op de achtergrond gaan we verder met het ontwikkelen van een duurzame oplossing.
