### ISSUE TITLE
Syncfeed API: filteren op attribuut werkt niet

### ISSUE THREAD

**Issue by jordibeen** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#85]
Volgens de [de documentatie van de SyncFeed API](https://opendata.tweedekamer.nl/documentatie/syncfeed-api) is het mogelijk om argumenten te gebruiken om het verzoek te filteren op hun onderliggende attributen. Ik lees dat buiten `category` en `skiptoken` het ook mogelijk is om als URL parameter `<attribuut>=<waarde>` mee te sturen, hierbij staat vermeld:
>Geeft een feed waarin iedere entiteit een attribuut met een specifieke waarde heeft 

Echter, wanneer ik entiteiten van de categorie "Document" probeer op te halen, en hierbij probeer te filteren op Documenten waarvan het `<vergaderjaar>` attribuut "2021-2022" bevat, krijg ik nog steeds alle Documenten terug.

---

## Voorbeeld:
**URL**
https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed?category=Document&vergaderjaar=2021-2022

**Verwachting**
Een resultaat met Documenten uit vergaderjaar 2021-2022.

**Resultaat**
Alle Documenten, ongeacht de waarde van het vergaderjaar attribuut.

---

Het probleem lijkt niet Document-specifiek, zo geven de onderliggende queries ook niet het verwachte resultaat:
- https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed?category=Persoon&achternaam=Rutte
- https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed?category=Fractie&afkorting=Krol
- https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed?category=Commissie&afkorting=NAA

---

Kunnen jullie er voor zorgen dat het mogelijk is om entiteiten te filteren op hun attributen, zoals vermeld staat in de documentatie? Alvast bedankt!

**Comment by jordibeen** [comment]
Hallo! Zouden jullie een tijdsindicatie kunnen geven voor wanneer het filteren van entiteiten op basis van een attribuut zal werken? Vriendelijk bedankt.

**Comment by OpenDataPortaal** [comment]
Het blijkt dat deze functie nooit in de programmatuur van de SyncFeed API heeft gezeten. Door de manier waarop de API is opgebouwd, is het helaas ook niet mogelijk om een dergelijke functie in te bouwen. Dit zou namelijk betekenen dat er per verzoek door alle .xml's heengegaan zou moeten worden, hetgeen teveel capaciteit kost om tot acceptabele reactietijden te komen. Het is met de [OData API](https://opendata.tweedekamer.nl/documentatie/odata-api) wel mogelijk om te filteren op specifieke attributen.

Tot onze spijt heeft dit al onverhoopt enige tijd in de documentatie gestaan zonder dat intern opgemerkt is dat dit niet correct is. We hebben dit nu uit de [documentatie](https://opendata.tweedekamer.nl/documentatie/syncfeed-api) gehaald maar begrijpen vanzelfsprekend dat dit niet het antwoord is waarop gewacht werd. Onze excuses hiervoor.
