### ISSUE TITLE
Niet mogelijk om referentiedocument terug te vinden dmv '$expand=*'

### ISSUE THREAD

**Issue by TheBeast762** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#87]
Hieronder is een opgehaald document zichtbaar, specifieke url: https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Document/ec9315bf-e1d1-422e-a8fb-0000932ed927

![image](https://user-images.githubusercontent.com/27029259/196181114-7cb3c46b-8224-4bf3-97bf-62f502d894a9.png)

Hierin staat onder footnote 2 een verwijzing naar een ander document (dmv een documentnummer).
Met het gebruik van $expand=* op de overkoepelende "Zaak" krijg ik het volgende terug als JSON:

![image](https://user-images.githubusercontent.com/27029259/196186161-0f4a609a-ead9-4427-b091-f69d948895cb.png)

Dan zien we bovenin metadata en onderin de gerelateerde data van de expand: ('Activiteit' tot en met 'Document').
'ZaakActor' bevat de betrokken mensen bij deze zaak.
'Document' bevat:
   [0]: Antwoord schriftelijke vragen
   [1]: Mededeling (uitstel antwoord)
   [2]: Schriftelijke vragen 

Geen van deze documenten betreffen "uw antwoorden op eerdere vragen over dit onderwerp?" zoals we zien bij footnote 2.
Mij is het dus niet gelukt om de gerelateerde referentie terug te vinden.

Is dit wel mogelijk? Zoja hoe dan?

**Comment by OpenDataPortaal** [comment]
De referentie naar het Document zit alleen in het oorspronkelijke Document (dus de pdf) met de beantwoorde Kamervragen, en is in het bronsysteem in de metadata niet opgenomen met een referentie naar het DocumentNummer in de footnote.
In dit geval is het dus helaas niet mogelijk om via een expand de gerelateerde referentie terug te vinden. Wel kan dat natuurlijk door daarna op het DocumentNummer te zoeken: https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Document?&$filter=DocumentNummer%20eq%20%272018D52471%27

Het gaat er dus om of in het bronsysteem deze referentie -handmatig- wordt gelegd en dat is hier niet. 

Een voorbeeld waar dat (vaak) wel gebeurt zijn aangenomen moties met een kabinetsreactie, zoals bij deze: https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Zaak?&$filter=Nummer%20eq%20%272021Z20615%27&$expand=*
Daar zie je dat het veld GerelateerdNaar refereert aan de brieven van de regering die betrekking hebben op de motie.
