### ISSUE TITLE
Zoeken op inhoud

### ISSUE THREAD

**Issue by Stratoprutser** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#88]
Ik wil graag zoeken op de inhoud van documenten, vergelijkbaar met de zoekfunctie op https://www.tweedekamer.nl/zoeken?qry=groningen&cfg=tksearch&sta=1&srt=date%3Adesc%3Adate maar het lijkt er op dat de inhoud van de documenten niet doorzoekaar is, of vergis ik mij?

**Comment by OpenDataPortaal** [comment]
Dat is correct. De API's zijn primair bedoeld voor dataleverantie. Via de SyncFeed-API kun je de data binnenhalen en vervolgens zelf een applicatie bouwen om de inhoud te doorzoeken. Via de OData-API doorzoek je de metadata van de documenten, maar niet de inhoud daarvan. De inhoud van de documenten kun je doorzoeken via www.tweedekamer.nl of via officiële bekendmakingen.

**Comment by Stratoprutser** [comment]
Oh echt? Moet ik die dan gaan scrapen om een rss feed te maken over een onderwerp waar ik de Kamerstukken over wil volgen? :/

**Comment by OpenDataPortaal** [comment]
Als het een RSS-feed moet worden is dat inderdaad de enige optie. Enkel op [officielebekendmakingen.nl](https://www.officielebekendmakingen.nl/) wordt ook de volledige inhoud van documenten gepubliceerd. Officiële bekendmakingen heeft ook [een eigen API](https://www.overheid.nl/help/officiele-bekendmakingen/bestanden-en-hergebruik).

Het is eventueel wel mogelijk om via e-mailattenderingen op de hoogte te blijven van de resultaten van een zoekopdracht op de website: https://www.tweedekamer.nl/emailattenderingen

**Comment by eiland-asbl** [comment]
Ok het duurde even maar zo dan maar. 
[tk_rss.php.txt](https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/files/10726635/tk_rss.php.txt)

**Comment by Stratoprutser** [comment]
Ok, het duurde even, maar... 
[tk_rss.php.txt](https://github.com/TweedeKamerDerStaten-Generaal/OpenDataPortaal/files/10726733/tk_rss.php.txt)
