### ISSUE TITLE
Syncfeed Besluit 500

### ISSUE THREAD

**Issue by jvanveen** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#89]
Interesante data! Ik ben nieuw met deze API, maar ik krijg een fout als ik alle besluiten wil ophalen via Syncfeed (Is dat hetzelfde als Feedsync trouwens?):

```bash
➜  tmp git:(main) ✗ wget https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed\?category\=Besluit
--2022-10-26 20:45:10--  https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed?category=Besluit
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving gegevensmagazijn.tweedekamer.nl (gegevensmagazijn.tweedekamer.nl)... 20.82.52.30
Connecting to gegevensmagazijn.tweedekamer.nl (gegevensmagazijn.tweedekamer.nl)|20.82.52.30|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2022-10-26 20:45:41 ERROR 500: Internal Server Error.
```
Moet ik misschien de resultatenset limiet meegeven?

**Comment by OpenDataPortaal** [comment]
Het probleem met entiteiten van de entiteitsoort Besluit in de SyncFeed API lijkt hetzelfde probleem te zijn dat voor ZaakActor bestond (#84). We hebben ernaar gekeken en het zou nu verholpen moeten zijn. Als dit niet het geval is dan horen we dat graag (incl. tijdstip van de poging zodat we in de logs kunnen kijken). De SyncFeed API is een intern ontwikkelde afgeleide van FeedSync.

**Comment by jvanveen** [comment]
Top! Die endpoint doet het weer. Bedankt voor de snelle fix.

**Comment by OpenDataPortaal** [comment]
Er is een tijdelijke oplossing geïmplementeerd die ervoor zou moeten zorgen dat de entiteitsoort Besluit beschikbaar blijft in de SyncFeed API. Op de achtergrond gaan we verder met het ontwikkelen van een duurzame oplossing.
