### ISSUE TITLE
Open API TweedeKamer beschikbaar via Cross Domain 

### ISSUE THREAD

**Issue by maxvankampen** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#92]
De Tweedekamer API is niet cross-domain bereikbaar. Ik krijg met een Javascript `fetch` nog steeds de error `CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource`.

Ik heb de Tweedekamer API cross-domain beschikbaar gemaakt via [tweedekamer.aliconnect.nl/api](https://tweedekamer.aliconnect.nl/api). Daar is tevens een OAS / Open API Specificatie te downloaden. Deze is te bekijken met [editor.swagger.io](https://editor.swagger.io/?url=https://aliconnect.nl/v1/client(7b28d899-9409-4e15-a077-03c72db5a9f6)/openapi). Je kan gebruik maken van de [Try it out] button. De POST, PATCH en DELETE methoden zijn niet beschikbaar, deze API is alleen lezen. De demo applicatie is te bekijken op [tweedekamer.aliconnect.nl](https://tweedekamer.aliconnect.nl/).

**Comment by OpenDataPortaal** [comment]
Bedankt voor het attenderen! Zoals in #71 is aangegeven zijn we niet van plan CORS mogelijk te maken. Vooralsnog hebben we er geen bezwaar op als dit via een omweg wel mogelijk gemaakt wordt.
