### ISSUE TITLE
Type GewijzigdOp niet overal gelijk

### ISSUE THREAD

**Issue by jorisrs** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#93]
Niet per sé fout, maar ik vraag mij af waarom er bij sommige entiteiten (bv KamerstukDossier of Document) het type van GewijzigdOp 'datetimeoffset' is en bij andere entiteiten (bv Persoon) het 'datetime2' is

**Comment by OpenDataPortaal** [comment]
De betreffende entiteitsoorten komen uit verschillende bronsystemen en als gevolg daarvan via andere pijplijnen het Gegevensmagazijn binnen. Tussen de pijplijnen bestaat kennelijk een inconsistentie in de toekenning van het datumformat van de waarde van het attribuut GewijzigdOp. We gaan hiermee aan de slag.

Naar aanleiding van #78 zijn we ook bezig met een bredere inventarisatie om datumformats zoveel mogelijk gelijk te trekken in het Gegevensmagazijn. Dit is echter vrij bewerkelijk daar we graag zien dat de aanpassingen op bronsysteemniveau worden gedaan - waardoor het over meerdere schijven loopt - zodat er geen transformaties binnen het Gegevensmagazijn plaatsvinden.

**Comment by OpenDataPortaal** [comment]
De inconsistentie in GewijzigdOp is opgelost. We zijn daarnaast bezig met #78.
