### ISSUE TITLE
Feedpagina SyncFeed API in XML aanleveren

### ISSUE THREAD

**Issue by OpenDataPortaal** [TweedeKamerDerStaten-Generaal/OpenDataPortaal#94]
Momenteel worden de [feedpagina's van de SyncFeed API](https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed) niet aangeleverd in XML; de pagina's van [specifieke entiteiten](https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Entiteiten/93b425f9-c0e0-47cc-8798-0aaacfc8e895) wel. Dit moet worden aangepast zodat ook de feedpagina's in XML worden aangeleverd.

**Comment by renevoorburg** [comment]
De feed is correcte XML, alleen worden niet de juiste mime type headers meegestuurd. Hierdoor tonen browsers de feed niet als XML. Een correcte mime type is text/xml.

**Comment by OpenDataPortaal** [comment]
We zijn erachter dat verchillende browsers hier anders mee omgaan. De SyncFeed is gebasseed op Atom en heeft daarom de mime type application/atom+xml. Chrome, bijvoorbeeld, rendert dit echter als text/plain. Hoe het nu geïmplementeerd is lijkt correct te zijn.
